In [ ]:
import torch

torch.__version__

'2.11.0+cpu'

In [ ]:
scalar = torch.tensor(3)
scalar, scalar.ndim, scalar.item, scalar.shape

(tensor(3), 0, <function Tensor.item>, torch.Size([]))

In [ ]:
vector = torch.tensor([1,2,3])
vector, vector.ndim, vector.item, vector.shape

(tensor([1, 2, 3]), 1, <function Tensor.item>, torch.Size([3]))

In [ ]:
matrix = torch.tensor([[1,2,3], [4,5,6]])
matrix, matrix.ndim, matrix.item, matrix.shape

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 2,
 <function Tensor.item>,
 torch.Size([2, 3]))

In [ ]:
tensor = torch.tensor([[[1, 2, 3], [3, 6, 9],[2, 4, 5]]])
tensor, tensor.ndim, tensor.item, tensor.shape

(tensor([[[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]]]),
 3,
 <function Tensor.item>,
 torch.Size([1, 3, 3]))

In [ ]:
random = torch.rand(size=(2,3))
random

tensor([[0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317]])

In [ ]:
zeros = torch.zeros(size=(2,3))
ones = torch.ones(size=(2,3))
zeros, ones

(tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]))

In [ ]:
range = torch.arange(2, 20, 3)
range

tensor([ 2,  5,  8, 11, 14, 17])

In [ ]:
ten_zeros = torch.zeros_like(input=range)
ten_ones = torch.ones_like(input=range)
ten_zeros, ten_ones

(tensor([0, 0, 0, 0, 0, 0]), tensor([1, 1, 1, 1, 1, 1]))

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, device=None, requires_grad=False)
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [ ]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
some_tensor = torch.rand(3, 4)

print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}")

tensor([[0.1053, 0.2695, 0.3588, 0.1994],
        [0.5472, 0.0062, 0.9516, 0.0753],
        [0.8860, 0.5832, 0.3376, 0.8090]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [ ]:
tensor = torch.tensor([1, 2, 3])
tensor + 10, tensor - 10, tensor * 10, tensor / 10

(tensor([11, 12, 13]),
 tensor([-9, -8, -7]),
 tensor([10, 20, 30]),
 tensor([0.1000, 0.2000, 0.3000]))

In [ ]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([3, 4, 1])

torch.matmul(tensor1, tensor2)

tensor(14)

In [ ]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [ ]:
torch.manual_seed(42)

linear = torch.nn.Linear(in_features=2, out_features=6)

x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [ ]:
linear = torch.nn.Linear( in_features=2, out_features=3 )

output = linear( tensor_A )

print( f"Input => {tensor_A}" )
print( f"Weight => {linear.weight}" )
print( f"Bias => {linear.bias}" )
print( f"Output => {output}")

Input => tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
Weight => Parameter containing:
tensor([[ 0.1102,  0.5713],
        [ 0.0773, -0.2230],
        [ 0.1900, -0.1918]], requires_grad=True)
Bias => Parameter containing:
tensor([0.2976, 0.6313, 0.4087], requires_grad=True)
Output => tensor([[ 1.5504,  0.2626,  0.2152],
        [ 2.9135, -0.0288,  0.2117],
        [ 4.2765, -0.3202,  0.2082]], grad_fn=<AddmmBackward0>)


In [ ]:
a = torch.tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

b = torch.tensor([[ 0.1102,  0.5713],
        [ 0.0773, -0.2230],
        [ 0.1900, -0.1918]])

bias = torch.tensor([0.2976, 0.6313, 0.4087])

c = torch.tensor([[ 1.5504,  0.2626,  0.2152],
        [ 2.9135, -0.0288,  0.2117],
        [ 4.2765, -0.3202,  0.2082]])

d = torch.matmul(a, b.T) + bias
print( d )

tensor([[ 1.5504,  0.2626,  0.2151],
        [ 2.9134, -0.0288,  0.2115],
        [ 4.2764, -0.3202,  0.2079]])


In [ ]:
x = torch.arange(1, 100, 1)

print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
print(f"Mean: {x.type(torch.float32).mean()}")
print(f"Sum: {x.sum()}")

Minimum: 1
Maximum: 99
Mean: 50.0
Sum: 4950


In [ ]:
x.argmax(), x.argmin()

(tensor(98), tensor(0))

In [ ]:
tensor = torch.arange(10., 100., 10.)
tensor_float16 = tensor.type( torch.float16 )

tensor.dtype, tensor_float16.dtype

(torch.float32, torch.float16)

In [ ]:
x = torch.arange(1.0, 21.0)
x_reshaped = x.reshape(4, -1)
x_view = x.view(4, -1)

x_reshaped, x_view

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.],
         [11., 12., 13., 14., 15.],
         [16., 17., 18., 19., 20.]]),
 tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.],
         [11., 12., 13., 14., 15.],
         [16., 17., 18., 19., 20.]]))

In [ ]:
dim1 = torch.stack( (x, x, x), 0 )
dim2 = torch.stack( (x, x, x), 1 )

dim1, dim2

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
          15., 16., 17., 18., 19., 20.],
         [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
          15., 16., 17., 18., 19., 20.],
         [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
          15., 16., 17., 18., 19., 20.]]),
 tensor([[ 1.,  1.,  1.],
         [ 2.,  2.,  2.],
         [ 3.,  3.,  3.],
         [ 4.,  4.,  4.],
         [ 5.,  5.,  5.],
         [ 6.,  6.,  6.],
         [ 7.,  7.,  7.],
         [ 8.,  8.,  8.],
         [ 9.,  9.,  9.],
         [10., 10., 10.],
         [11., 11., 11.],
         [12., 12., 12.],
         [13., 13., 13.],
         [14., 14., 14.],
         [15., 15., 15.],
         [16., 16., 16.],
         [17., 17., 17.],
         [18., 18., 18.],
         [19., 19., 19.],
         [20., 20., 20.]]))

In [ ]:
xs = x.squeeze()
xu = x.unsqueeze(dim=1)

xs, xu

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
         15., 16., 17., 18., 19., 20.]),
 tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.],
         [11.],
         [12.],
         [13.],
         [14.],
         [15.],
         [16.],
         [17.],
         [18.],
         [19.],
         [20.]]))

In [ ]:
a = torch.tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

a.permute(1,0)

tensor([[1., 3., 5.],
        [2., 4., 6.]])

In [ ]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape


x[0], x[0][0], x[0][0][0], x[:, 0], x[:, :, 1]

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([1, 2, 3]),
 tensor(1),
 tensor([[1, 2, 3]]),
 tensor([[2, 5, 8]]))

In [ ]:
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
import torch
import random

RANDOM_SEED=42
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.random.manual_seed(seed=RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])